### ISSUE TITLE
logo in header next to longform

### ISSUE THREAD

**Issue by astratagem** [TheTempleNews/longform#1]

**Comment by pmcc8** [comment]
Maybe just use the fontface Old English MT?

**Comment by astratagem** [comment]
I'm open to that but only if it's licensed for web use, which I don't
believe it is. Also IIRC, in comparison to the logo, it looks a little…
weird.

On Sunday, August 24, 2014, pmcc8 notifications@github.com wrote:

> Maybe just use the fontface Old English MT?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TheTempleNews/longform/issues/1#issuecomment-53210501
> .

## 

_Chris Montgomery_
chris@montchr.io
github.com/montchr

Web Developer
School of Media and Communication
Temple University
smc.temple.edu
fork@temple.edu

Web Editor
The Temple News
temple-news.com
web@temple-news.com

Vice President
Aperture Agency
apertureagency@gmail.com

_Sous les pavés, la plage_.

**Comment by astratagem** [comment]
Okay, it is available for web use, but apparently only through [MyFonts for $29, here](https://www.myfonts.com/fonts/mti/old-english-text/). I'd say let's just use the logo image we have.

**Comment by astratagem** [comment]
@amaehrer @pmcc8 I think it actually looks real nice with just the text in this font. Do we need the logo there?

![screenshot 2014-08-24 22 07 46](https://cloud.githubusercontent.com/assets/1757914/4025598/ad564d2c-2bfd-11e4-8f06-49f4493ef464.png)

Logo or not, there should be a way to link back to the main site…

Here's my recommendation:
1. Change site name to simply "Longform"
2. Link "The Temple News" text (not logo, but text) to main site

**Comment by pmcc8** [comment]
Could we see what it looks like with the logo? 

Other options might include in the footer or top of the featured image.

Still link them per your recommendation.

**Comment by astratagem** [comment]
Sure, I'll work on that.

On Sun, Aug 24, 2014 at 10:20 PM, pmcc8 notifications@github.com wrote:

> Could we see what it looks like with the logo?
> 
> Still link them per your recommendation.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TheTempleNews/longform/issues/1#issuecomment-53221317
> .

## 

_Chris Montgomery_
chris@montchr.io
github.com/montchr

Web Developer
School of Media and Communication
Temple University
smc.temple.edu
fork@temple.edu

Web Editor
The Temple News
temple-news.com
web@temple-news.com

Vice President
Aperture Agency
apertureagency@gmail.com

_Sous les pavés, la plage_.

**Comment by astratagem** [comment]
Boom. Check it.

![screenshot 2014-08-24 22 54 55](https://cloud.githubusercontent.com/assets/1757914/4025777/3b099958-2c03-11e4-9738-17df2ab66a0b.png)

**Comment by pmcc8** [comment]
I think this looks much better.

Will it individually link?

**Comment by astratagem** [comment]
Yep. Done.

**Comment by pmcc8** [comment]
Looks very clean. 

Fantastic work.

**Comment by astratagem** [comment]
![Thanks!](http://www.reactiongifs.com/r/lvar.gif)

**Comment by pmcc8** [comment]
<a href="http://imgur.com/bcMqxmW"><img src="http://i.imgur.com/bcMqxmW.gif" title="Hosted by imgur.com" /></a>
