### ISSUE TITLE
add support for co-authors plus

### ISSUE THREAD

**Issue by astratagem** [TheTempleNews/longform#10]

**Comment by astratagem** [comment]
Added. Looks a little weird in all caps though. @amaehrer @pmcc8 your thoughts?

![screenshot 2014-08-24 14 14 32](https://cloud.githubusercontent.com/assets/1757914/4024142/992af674-2bba-11e4-9d5d-b237e428f084.png)

**Comment by amaehrer** [comment]
Can we do the "and" in lowercase? If not, it should still be OK.

**Comment by astratagem** [comment]
Definitely. I agree it would be better.

**Comment by astratagem** [comment]
How's this?

![screenshot 2014-08-24 14 25 23](https://cloud.githubusercontent.com/assets/1757914/4024188/0a91ab7c-2bbc-11e4-91c9-201286317516.png)

**Comment by amaehrer** [comment]
Definitely better.

**Comment by astratagem** [comment]
Cool. I'll implement this then.

**Comment by astratagem** [comment]
Done.
