### ISSUE TITLE
change permalink

### ISSUE THREAD

**Issue by astratagem** [TheTempleNews/longform#15]
Currently permalink is `/hello-world/`. Should be something like `/pain-game/` or `/pain-and-the-game/`.

**Comment by pmcc8** [comment]
Fixed.

**Comment by astratagem** [comment]
Edit: Sorry, wrong issue.

**Comment by astratagem** [comment]
Still looks the same to me… is that WordPress being weird again?

**Comment by astratagem** [comment]
I like the `/pain-game/`.
