### ISSUE TITLE
Sharing

### ISSUE THREAD

**Issue by amaehrer** [TheTempleNews/longform#17]
Not a big deal, but is there a way to get the featured image to show up when we share on FB tomorrow and/or add some sort of share button to the page?

**Comment by astratagem** [comment]
I'm going to test this by temporarily making the post public.

:thumbsdown: on the share button tho. If people want to share, they will.

**Comment by astratagem** [comment]
Okay, tested, and this is the first image that came up for me:

![screenshot 2014-08-24 23 27 53](https://cloud.githubusercontent.com/assets/1757914/4025913/df03c9ee-2c07-11e4-9023-990c6447652d.png)

I can install an SEO plugin to see if that changes anything…

**Comment by astratagem** [comment]
Also, that text could be better. Hopefully the SEO thing will take care of that.

**Comment by astratagem** [comment]
Installed All-In-One SEO plugin, configured, retried with FB. Got a different image, refreshed several times and got the same set of choices. I'd try it out yourselves to see if we can expect that's what people will see. Any idea why it's picking this particular image first?

![screenshot 2014-08-24 23 34 16](https://cloud.githubusercontent.com/assets/1757914/4025941/016384c4-2c09-11e4-9878-217050babe0e.png)

**Comment by astratagem** [comment]
And damn, that text is no better… I know the text will be good in Google search results, but I don't know where FB gets its data from.

**Comment by pmcc8** [comment]
http://stackoverflow.com/questions/1138460/how-does-facebook-sharer-select-images

Double clicking text makes it editable before sharing. This of course would be done by the user.

**Comment by astratagem** [comment]
Yeahhh… considering I never knew that, and I doubt many others do, that unfortunately won't help us too much.

**Comment by pmcc8** [comment]
http://www.pragmaticworld.com/articles/view/Facebook-shares-wrong-image-Heres-a-fix
