### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by amaehrer** [TheTempleNews/longform#19]
Possible to get publication date somewhere on the page?

**Comment by astratagem** [comment]
Sure. Can it wait till after launch? I still have a lot to do with the main site before tomorrow and I am not available tomorrow.

**Comment by pmcc8** [comment]
This can wait till after launch.

**Comment by pmcc8** [comment]
Added.

**Comment by astratagem** [comment]
Nice, seems like a good place for it.

On Tue, Aug 26, 2014 at 1:54 PM, pmcc8 notifications@github.com wrote:

> Added.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TheTempleNews/longform/issues/19#issuecomment-53462022
> .

## 

_Chris Montgomery_
Developer of Webs
chris@montchr.io
github.com/montchr

Developer of Webs
School of Media and Communication
Temple University
smc.temple.edu
fork@temple.edu

_Sous les pavés, la plage_.
