### ISSUE TITLE
add support for dek/excerpt

### ISSUE THREAD

**Issue by astratagem** [TheTempleNews/longform#2]
Between hed and byline on front (?) and after both on post (?).

**Comment by astratagem** [comment]
Done. Deks can be added in the excerpt field. Note that if one does not exist, WordPress will try to automatically define one. /cc @pmcc8 @amaehrer

**Comment by astratagem** [comment]
Derp. Didn't set this up for the front page yet.

**Comment by astratagem** [comment]
Okay, fixed now.

**Comment by amaehrer** [comment]
Looks good. Only problem is that when you shrink the browser (and I'm guessing for mobile), the hed/dek go below the screen and the dek remains in white so it's very hard to see.

**Comment by astratagem** [comment]
@amaehrer Good catch. Thanks, I'll fix that.

**Comment by astratagem** [comment]
> Done. Deks can be added in the excerpt field. Note that if one does not exist, WordPress will try to automatically define one.

/cc @pmcc8

**Comment by astratagem** [comment]
@pmcc8 If you'd like, we could prevent that from happening in the future by using Advanced Excerpt… though I don't see the point in installing and configuring that when we could just say "always include an excerpt/dek."

**Comment by astratagem** [comment]
Okay, dek is fixed up. @amaehrer
