### ISSUE TITLE
Chop, boom.

### ISSUE THREAD

**Issue by amaehrer** [TheTempleNews/longform#21]
Possible to make a post that directs to "Chop, boom" on this new longform site?

**Comment by astratagem** [comment]
Hmm. Good point. I'll have to think about how that could be accomplished seamlessly.

**Comment by astratagem** [comment]
Honestly, the best option might even be to migrate Chop Boom to this site, using this theme. What do you think about that?

**Comment by astratagem** [comment]
It would be sad to see all that work we did disappear though… but anything else would probably not integrate so well if you want it to show up on the main page as another post…

**Comment by amaehrer** [comment]
I don't want to see it change that drastically, especially because of all of the work you guys did on it. But it would be nice if we could somehow integrate it here, because it might get more traffic as people read this story.

**Comment by astratagem** [comment]
Right. I agree.

Okay, so I could potentially rig this so we create Chop Boom as a post just as you did for the new story, but only give it a **title**, **excerpt**, and **featured image**. Then I could set up a redirection that would always point `http://longform.temple-news.com/chop-boom` to `http://chopboom.temple-news.com`.

Actually, that makes a lot of sense and it would take five minutes to set up. Let's do it.

**Comment by amaehrer** [comment]
Awesome, sounds good.

**Comment by astratagem** [comment]
What should the featured image be? I can set this post and redirection up.

**Comment by astratagem** [comment]
I strongly nominate this one:

![Thanks, Hua](http://chopboom.com/app/uploads/2015/04/21Water.jpg)

**Comment by astratagem** [comment]
Or this, but it's not really Temple-specific:

![Thanks again, Hua](http://162.243.197.229/app/uploads/2015/04/JN8A3637.jpg)

**Comment by amaehrer** [comment]
Agreed.

**Comment by amaehrer** [comment]
I like the rowing one.

**Comment by astratagem** [comment]
Okay, I'll set that up.

**Comment by astratagem** [comment]
That one is maybe not the best, judging by the amount of stuff going on where the subject of interest (rowing team) is. 

![screenshot 2014-08-25 00 44 27](https://cloud.githubusercontent.com/assets/1757914/4026236/9baee1f0-2c12-11e4-9ad9-b0885ccafdb3.png)

**Comment by amaehrer** [comment]
How about this one?
![screen shot 2014-08-25 at 12 48 02 am](https://cloud.githubusercontent.com/assets/8527355/4026248/07e898b6-2c13-11e4-9b05-ff677b6edaff.png)

**Comment by astratagem** [comment]
I was working on that one too. Check it out. I think it works, but it's still a little difficult to read the white text over the guy's white pants. But I suggest @pmcc8 can keep playing with the featured image crop to get the positioning better if you want. Not sure if it'll get much better though.

**Comment by astratagem** [comment]
What should the author name be? I think it should be attributed to the admin user (`ttnlongform`) but it should have a better display name, like "The Temple News". Yeah?

**Comment by astratagem** [comment]
Or "The Temple News Longform".

**Comment by amaehrer** [comment]
Let's make it "The Temple News"

**Comment by astratagem** [comment]
Redirection is now active. You won't be able to get to the post without going through the Dashboard.

> Let's make it "The Temple News"

Done.

**Comment by amaehrer** [comment]
Featured photo looks a little odd below the one we have for the track story. Maybe something on the final season page? One of the gymnastics ones?

**Comment by amaehrer** [comment]
Or perhaps just a screenshot of the boat loop?

**Comment by astratagem** [comment]
> Or perhaps just a screenshot of the boat loop?

Nah, boat loop is kinda meh as a hook.

My nominations:

![](http://162.243.197.229/app/uploads/2014/04/JN8A3659.jpg)

![](http://chopboom.com/app/uploads/2015/04/JN8A7602.jpg)

![](http://162.243.197.229/app/uploads/2015/04/JN8A7576.jpg)

![](http://162.243.197.229/app/uploads/2015/04/140223BOT-12.jpg)

![](http://chopboom.com/app/uploads/2015/04/JacobColon_CrewCoach_Sports_11-19-13_131.jpg)

**Comment by amaehrer** [comment]
I like gymnastics protests and guy with the mic.

**Comment by astratagem** [comment]
Mic guy, at different viewport widths:

![screenshot 2014-08-25 01 12 07](https://cloud.githubusercontent.com/assets/1757914/4026351/731c6f10-2c16-11e4-9ed9-7aff8f05a14b.png)
![screenshot 2014-08-25 01 11 58](https://cloud.githubusercontent.com/assets/1757914/4026352/731c6808-2c16-11e4-8369-ccae9a2a2bad.png)
![screenshot 2014-08-25 01 11 40](https://cloud.githubusercontent.com/assets/1757914/4026353/731c8e5a-2c16-11e4-82df-0d1ceb41fa32.png)

**Comment by astratagem** [comment]
And protests:

![screenshot 2014-08-25 01 15 33](https://cloud.githubusercontent.com/assets/1757914/4026362/e0dab08e-2c16-11e4-90d7-198535769dc5.png)
![screenshot 2014-08-25 01 15 14](https://cloud.githubusercontent.com/assets/1757914/4026363/e0e131f2-2c16-11e4-92d3-d482cd986719.png)

**Comment by astratagem** [comment]
I like mic guy, mainly because protest is too busy, esp. with the text on signs.

**Comment by amaehrer** [comment]
Yeah, mic guy is better. Text is hard to read on the protest. Not our best photo, but works best with this situation.

**Comment by astratagem** [comment]
Done.
