### ISSUE TITLE
Change tag color on menu page.

### ISSUE THREAD

**Issue by pmcc8** [TheTempleNews/longform#23]
The word 'Investigations' is coming up as #85b0bf when you are looking at the stories.
![screen shot 2014-08-25 at 12 22 24 am](https://cloud.githubusercontent.com/assets/3536743/4026141/71f2f3ea-2c0f-11e4-8f2b-45927a68304e.png)

**Comment by astratagem** [comment]
That can be changed by going to Dashboard > Appearance > Customize > Novella Options.
