### ISSUE TITLE
Crashing on Chrome Desktop

### ISSUE THREAD

**Issue by pmcc8** [TheTempleNews/longform#27]
Database crash?

**Comment by astratagem** [comment]
Wow. Looking into it…

**Comment by astratagem** [comment]
Restarted MySQL. Resolved. Strange. Keep an eye on it.

**Comment by astratagem** [comment]
Actually I'm going to take it down for a few minutes to take a snapshot. Should have set up automatic backups when I started the server. Didn't realize it was a one-time-only thing. But snapshots can be done by powering off.

Might start up a new server with backups at some point…

**Comment by pmcc8** [comment]
Okay. Everything seems good for now.
