### ISSUE TITLE
site title typography adjustments

### ISSUE THREAD

**Issue by astratagem** [TheTempleNews/longform#3]

**Comment by astratagem** [comment]
Baskerville was suggested as a replacement at one point. It's already set in Baskerville. Closing.

**Comment by amaehrer** [comment]
Possible to have it unitalicized and not all caps?

**Comment by astratagem** [comment]
Sure, I can do that. :)

**Comment by astratagem** [comment]
@amaehrer Goooood call. I like this better. 

![screenshot 2014-08-24 22 07 46](https://cloud.githubusercontent.com/assets/1757914/4025572/a413972a-2bfc-11e4-805a-f1ac05f3a666.png)
