### ISSUE TITLE
Drop caps

### ISSUE THREAD

**Issue by pmcc8** [TheTempleNews/longform#4]
I can make a faux one, but it breaks the line spacing.

They should be started before the chapters.

**Comment by astratagem** [comment]
@pmcc8 The theme should already handle drop caps with CSS, for the first paragraph of each chapter.

Is "before the chapters" different than what it already does?

![](http://aesopstoryengine.com/wp-content/uploads/2014/08/Image-2014-08-01-at-7.35.51-AM-1024x808.png)

**Comment by pmcc8** [comment]
![screen shot 2014-08-23 at 8 46 02 pm](https://cloud.githubusercontent.com/assets/3536743/4022282/0ecfe3c8-2b28-11e4-9629-5a73df0005d0.png)

Here is what I see in the preview.

I meant after the chapter titles. We would also need one for the very first paragraph, which is untitled.

**Comment by astratagem** [comment]
Ah, I see. That paragraph has to have a class of `.lead`. So for example:

```
<p class="lead">Ebony Moore arrived at Temple in 2009, a transplant of Missouri, Georgia and Alabama. She grew up in St. Louis in what she describes as an easygoing, liberal family.</p>
```

**Comment by astratagem** [comment]
Check out any of the posts on [the Novella demo site](http://aesopthemes.com/novella/?preview&utm_referrer=http%3A%2F%2Faesopstoryengine.com%2Flibrary%2Fnovella%2F).

**Comment by pmcc8** [comment]
Got it. Thanks.
