### ISSUE TITLE
Parallax still not working

### ISSUE THREAD

**Issue by pmcc8** [TheTempleNews/longform#6]
Possible max height restriction.

**Comment by astratagem** [comment]
Can you show me an example?

**Comment by astratagem** [comment]
And can you explain exactly what isn't working?

Looks like it's working okay to me… except that it's very very subtle. I added a test image in the main post – a screencap of Tim and Eric running into a a familiar building. There doesn't seem to be a way to control the speed of the parallax effect as there was in previous version of ASE. Anyway, I think parallax can get a little disorienting for viewers so subtle is probably better.

But do please let me know if it is actually not working.

**Comment by pmcc8** [comment]
I phrased this wrong.

Parallax is working as intended. I think I'm looking closer to the scroll kit seen on http://aesopthemes.com/novella/?preview&utm_referrer=http%3A%2F%2Faesopstoryengine.com%2Flibrary%2Fnovella%2F

It uses the class 'aesop-stacked-image'.

If we can't get something like this working, it will not be a problem.

**Comment by astratagem** [comment]
Ok I'll take a look when I get home.

On Sunday, August 24, 2014, pmcc8 notifications@github.com wrote:

> I phrased this wrong.
> 
> Parallax is working as intended. I think I'm looking closer to the scroll
> kit seen on
> http://aesopthemes.com/novella/?preview&utm_referrer=http%3A%2F%2Faesopstoryengine.com%2Flibrary%2Fnovella%2F
> 
> It uses the class 'aesop-stacked-image'.
> 
> If we can't get something like this working, it will not be a problem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TheTempleNews/longform/issues/6#issuecomment-53210422
> .

## 

_Chris Montgomery_
chris@montchr.io
github.com/montchr

Web Developer
School of Media and Communication
Temple University
smc.temple.edu
fork@temple.edu

Web Editor
The Temple News
temple-news.com
web@temple-news.com

Vice President
Aperture Agency
apertureagency@gmail.com

_Sous les pavés, la plage_.

**Comment by astratagem** [comment]
Sorry, that link doesn't go to any place directly (happened to me earlier)… can you tell me where to find it?

**Comment by pmcc8** [comment]
The Glare of Kingston Hill story. Scroll down.

**Comment by astratagem** [comment]
Ahhhhh, okay. Got it. Looks like that's the Gallery component, judging by the `.aesop-gallery-component` class on the container of `.aesop-stacked-img`. But I don't even see that in the Add Component list… weird…

Looking into this one… because the gallery there does look real nice.

**Comment by astratagem** [comment]
Derp. Check the sidebar – there's a post type called "Galleries"… I'd guess that's where we should look…

**Comment by astratagem** [comment]
Follow the instructions in the aside metabox on the New Gallery / Edit Gallery page. When you add the WP gallery through Add Media, choose the type in the select dropdown after you've chosen the images. There is an option for "Stacked Parallax". [Check it out working here on our site](http://longform.temple-news.com/stacked-image-test/).

**Comment by pmcc8** [comment]
This is amazing.

You are amazing.
