### ISSUE TITLE
Remove "Read More" at bottom temporarily

### ISSUE THREAD

**Issue by pmcc8** [TheTempleNews/longform#8]

**Comment by astratagem** [comment]
@pmcc8 You might need to publish the post for that to go away. Can you publish and set to private?

**Comment by astratagem** [comment]
That didn't work. Seems like the theme is a little buggy.

I've taken this out by setting `#novella-read-more` to `display: none;`. Until this is changed in the future, read more / additional posts shouldn't show up ever.
